import { useEffect, useState, type ComponentType, type ReactNode } from "react";
import { AlertTriangle, ArrowDown, ArrowUp } from "lucide-react";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import type { InterestLevel, LeadStatus, Solution } from "../types";
export function usePagedRows<T>(rows:T[],perPage=10){const [page,setPage]=useState(1);const pages=Math.max(1,Math.ceil(rows.length/perPage));const safePage=Math.min(page,pages);useEffect(()=>{if(page>pages)setPage(pages)},[pages]);const pageRows=rows.slice((safePage-1)*perPage,safePage*perPage);return {page:safePage,setPage,pages,pageRows,total:rows.length}}
export function TablePagination({page,setPage,pages,total,perPage=10}:{page:number;setPage:(p:number)=>void;pages:number;total:number;perPage?:number}){if(pages<=1)return null;const start=total===0?0:(page-1)*perPage+1;const end=Math.min(page*perPage,total);return <div className="flex flex-col items-center justify-between gap-3 border-t px-4 py-3 sm:flex-row"><p className="text-xs text-muted-foreground">A mostrar {start}–{end} de {total}</p><div className="flex items-center gap-1"><Button variant="outline" size="sm" disabled={page<=1} onClick={()=>setPage(page-1)}>Anterior</Button><span className="px-2 text-xs tabular-nums text-muted-foreground">Página {page} de {pages}</span><Button variant="outline" size="sm" disabled={page>=pages} onClick={()=>setPage(page+1)}>Seguinte</Button></div></div>}
export function PageTitle({title,subtitle,actions}:{title:string;subtitle?:string;actions?:ReactNode}){return <div className="mb-7 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div className="border-l-[3px] border-primary pl-4"><h1 className="text-[26px] font-semibold tracking-tight">{title}</h1>{subtitle&&<p className="mt-1.5 max-w-3xl text-sm leading-relaxed text-muted-foreground">{subtitle}</p>}</div>{actions&&<div className="flex flex-wrap gap-2">{actions}</div>}</div>}
export function KpiCard({label,value,change,icon:Icon,tone="default"}:{label:string;value:string|number;change?:string;icon:ComponentType<{className?:string}>;tone?:"default"|"critical"}){const up=!change?.startsWith("-");return <article className="group flex items-center gap-4 rounded-lg border bg-card p-5 shadow-sm transition-all hover:-translate-y-0.5 hover:border-primary/30 hover:shadow-md"><span className={cn("grid h-12 w-12 shrink-0 place-items-center rounded-lg transition-colors",tone==="critical"?"bg-destructive-soft text-destructive":"bg-primary/10 text-primary")}><Icon className="h-6 w-6"/></span><div className="min-w-0 flex-1"><p className="truncate text-[11px] font-semibold uppercase tracking-wide text-muted-foreground">{label}</p><div className="mt-1.5 flex items-baseline gap-2"><p className="text-[28px] font-semibold leading-none tabular-nums">{value}</p>{change&&<span className={cn("flex items-center gap-1 text-xs font-medium",tone==="critical"?"text-destructive":up?"text-success":"text-muted-foreground")}>{tone==="critical"?<AlertTriangle className="h-3.5 w-3.5"/>:up?<ArrowUp className="h-3.5 w-3.5"/>:<ArrowDown className="h-3.5 w-3.5"/>}{change}</span>}</div></div></article>}
export function InterestBadge({value}:{value:InterestLevel}){return <span className={cn("inline-flex rounded-full px-2.5 py-1 text-xs font-medium",value==="Alto"?"bg-success-soft text-success":value==="Médio"?"bg-warning-soft text-warning":"bg-muted text-muted-foreground")}>{value}</span>}
export function LeadStatusBadge({value}:{value:LeadStatus}){const critical=value==="Sem interesse";const info=value==="Reunião";const success=value==="Convertido";return <span className={cn("inline-flex items-center gap-1 rounded-full border px-2.5 py-1 text-xs font-medium",critical?"border-destructive bg-destructive-soft text-destructive":info?"border-info/20 bg-info-soft text-info":success?"border-success/20 bg-success-soft text-success":"border-border bg-muted text-muted-foreground")}>{critical&&<AlertTriangle className="h-3 w-3"/>}{value}</span>}
export function SolutionChip({value}:{value:Solution}){return <span className="inline-flex rounded-full bg-accent px-2.5 py-1 text-xs font-semibold text-accent-foreground">{value}</span>}
