import { useQuery } from "@tanstack/react-query";
import { Check, MailPlus, ShieldCheck, ShieldX, UserCog } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { PageHeader } from "@/components/shared/PageHeader";
import { StatusBadge } from "@/components/shared/StatusBadge";
import { api } from "@/lib/api/client";
import { toast } from "sonner";

const permissions = [{ area: "Utilizadores", super: true, moderator: true, support: true }, { area: "Denúncias e sanções", super: true, moderator: true, support: false }, { area: "Anúncios e legal", super: true, moderator: false, support: false }, { area: "Administradores", super: true, moderator: false, support: false }, { area: "Auditoria", super: true, moderator: false, support: false }];
export default function AdminsPage() { const { data = [] } = useQuery({ queryKey: ["admins"], queryFn: api.admins }); return <><PageHeader title="Administradores" description="Gira acessos, perfis e a protecção das contas administrativas." actions={<Button onClick={() => toast.success("Convite de demonstração preparado")}><MailPlus /> Convidar administrador</Button>} /><section className="surface overflow-hidden"><div className="divide-y">{data.map((admin) => <div key={admin.id} className="flex flex-wrap items-center gap-4 p-5"><span className="icon-bubble"><UserCog /></span><div className="min-w-0 flex-1"><p className="font-bold">{admin.name}</p><p className="text-xs text-muted-foreground">{admin.email} · {admin.lastSeen}</p></div><StatusBadge status={admin.active ? "activa" : "suspensa"} /><span className="rounded-full bg-primary-soft px-3 py-1 text-xs font-bold text-primary">{admin.role}</span><div className="flex items-center gap-2 text-xs"><ShieldCheck className={admin.twoFactor ? "text-success" : "text-warning"} />2FA {admin.twoFactor ? "activo" : "pendente"}</div><Button variant="outline" size="sm">Gerir</Button></div>)}</div></section><section className="surface mt-6 overflow-hidden"><div className="border-b p-5"><h2 className="font-extrabold">Matriz de permissões</h2><p className="text-sm text-muted-foreground">Visibilidade e acções disponíveis por perfil.</p></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-element text-left text-xs uppercase text-muted-foreground"><tr><th className="p-4">Área</th><th className="p-4 text-center">Super-admin</th><th className="p-4 text-center">Moderador</th><th className="p-4 text-center">Suporte</th></tr></thead><tbody>{permissions.map((item) => <tr key={item.area} className="border-t"><td className="p-4 font-semibold">{item.area}</td>{[item.super,item.moderator,item.support].map((allowed,index) => <td key={index} className="p-4 text-center">{allowed ? <Check className="mx-auto text-success" /> : <ShieldX className="mx-auto text-muted-foreground/40" />}</td>)}</tr>)}</tbody></table></div></section></>; }