import { useMemo, useState, type ReactNode } from "react";
import { flexRender, getCoreRowModel, getPaginationRowModel, getSortedRowModel, type ColumnDef, type SortingState, useReactTable } from "@tanstack/react-table";
import { ArrowUpDown, ChevronLeft, ChevronRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

export function DataTable<T>({ data, columns, mobileCard, selectable = false }: { data: T[]; columns: ColumnDef<T>[]; mobileCard?: (item: T) => ReactNode; selectable?: boolean }) {
  const [sorting, setSorting] = useState<SortingState>([]);
  const [rowSelection, setRowSelection] = useState({});
  const merged = useMemo<ColumnDef<T>[]>(() => selectable ? [{ id: "select", header: ({ table }) => <Checkbox aria-label="Seleccionar tudo" checked={table.getIsAllPageRowsSelected()} onCheckedChange={(value) => table.toggleAllPageRowsSelected(Boolean(value))} />, cell: ({ row }) => <Checkbox aria-label="Seleccionar linha" checked={row.getIsSelected()} onCheckedChange={(value) => row.toggleSelected(Boolean(value))} /> }, ...columns] : columns, [columns, selectable]);
  const table = useReactTable({ data, columns: merged, state: { sorting, rowSelection }, onSortingChange: setSorting, onRowSelectionChange: setRowSelection, getCoreRowModel: getCoreRowModel(), getSortedRowModel: getSortedRowModel(), getPaginationRowModel: getPaginationRowModel(), initialState: { pagination: { pageSize: 5 } } });
  return <div><div className="hidden overflow-hidden rounded-[1.4rem] border md:block"><Table><TableHeader className="bg-element/70">{table.getHeaderGroups().map((group) => <TableRow key={group.id}>{group.headers.map((header) => <TableHead key={header.id} className="h-12 text-xs font-bold uppercase text-muted-foreground">{header.isPlaceholder ? null : <button className="flex items-center gap-1.5" onClick={header.column.getToggleSortingHandler()}>{flexRender(header.column.columnDef.header, header.getContext())}{header.column.getCanSort() && <ArrowUpDown className="h-3.5 w-3.5" />}</button>}</TableHead>)}</TableRow>)}</TableHeader><TableBody>{table.getRowModel().rows.map((row) => <TableRow key={row.id} className="transition-colors hover:bg-primary-soft/60">{row.getVisibleCells().map((cell) => <TableCell key={cell.id} className="py-4">{flexRender(cell.column.columnDef.cell, cell.getContext())}</TableCell>)}</TableRow>)}</TableBody></Table></div><div className="space-y-3 md:hidden">{table.getRowModel().rows.map((row) => <div key={row.id} className="surface p-4">{mobileCard ? mobileCard(row.original) : row.getVisibleCells().map((cell) => <div key={cell.id}>{flexRender(cell.column.columnDef.cell, cell.getContext())}</div>)}</div>)}</div><div className="mt-4 flex items-center justify-between"><p className="text-xs text-muted-foreground">{Object.keys(rowSelection).length ? `${Object.keys(rowSelection).length} seleccionados · ` : ""}{data.length} registos</p><div className="flex gap-2"><Button variant="outline" size="icon" aria-label="Página anterior" onClick={() => table.previousPage()} disabled={!table.getCanPreviousPage()}><ChevronLeft /></Button><Button variant="outline" size="icon" aria-label="Página seguinte" onClick={() => table.nextPage()} disabled={!table.getCanNextPage()}><ChevronRight /></Button></div></div></div>;
}