import { useState } from "react";
import { Laptop, LockKeyhole, Moon, Save, ShieldCheck, Smartphone, Sun, UserRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { PageHeader } from "@/components/shared/PageHeader";
import { useTheme } from "@/components/layout/ThemeProvider";
import { toast } from "sonner";

export default function SettingsPage() { const { theme, toggle } = useTheme(); const [twoFactor, setTwoFactor] = useState(true); return <><PageHeader title="Definições" description="Actualize o seu perfil, segurança e preferências do back office." /><Tabs defaultValue="profile"><TabsList className="mb-5 rounded-full bg-element p-1"><TabsTrigger value="profile" className="rounded-full"><UserRound className="mr-2 h-4 w-4" />Perfil</TabsTrigger><TabsTrigger value="security" className="rounded-full"><LockKeyhole className="mr-2 h-4 w-4" />Segurança</TabsTrigger><TabsTrigger value="preferences" className="rounded-full"><Sun className="mr-2 h-4 w-4" />Preferências</TabsTrigger></TabsList><TabsContent value="profile" className="surface max-w-3xl p-6"><div className="grid gap-5 sm:grid-cols-2"><div><Label>Nome completo</Label><Input defaultValue="Deusineusio dos Santos" className="mt-2 rounded-full" /></div><div><Label>Email</Label><Input defaultValue="admin@mokamba.ao" className="mt-2 rounded-full" /></div><div><Label>Função</Label><Input value="Super-admin" readOnly className="mt-2 rounded-full bg-element" /></div><div><Label>Telefone</Label><Input defaultValue="+244 923 000 100" className="mt-2 rounded-full" /></div></div><Button className="mt-6" onClick={() => toast.success("Perfil actualizado")}><Save /> Guardar alterações</Button></TabsContent><TabsContent value="security" className="space-y-5"><section className="surface flex items-center gap-4 p-6"><span className="icon-bubble"><ShieldCheck /></span><div className="flex-1"><p className="font-bold">Autenticação em dois passos</p><p className="text-sm text-muted-foreground">Protege o acesso com um código temporário.</p></div><Switch checked={twoFactor} onCheckedChange={setTwoFactor} /></section><section className="surface overflow-hidden"><div className="border-b p-5"><h2 className="font-extrabold">Sessões activas</h2></div>{[["MacBook Pro", "Luanda · sessão actual", Laptop], ["iPhone", "Luanda · há 2 horas", Smartphone]].map(([name,detail,Icon]) => <div key={String(name)} className="flex items-center gap-4 border-b p-5 last:border-0"><span className="icon-bubble"><Icon className="h-5 w-5" /></span><div className="flex-1"><p className="font-bold">{String(name)}</p><p className="text-sm text-muted-foreground">{String(detail)}</p></div><Button variant="outline" size="sm">Terminar</Button></div>)}</section></TabsContent><TabsContent value="preferences" className="surface max-w-3xl p-6"><div className="flex items-center gap-4"><span className="icon-bubble">{theme === "dark" ? <Moon /> : <Sun />}</span><div className="flex-1"><p className="font-bold">Modo escuro</p><p className="text-sm text-muted-foreground">O tema fica guardado neste dispositivo.</p></div><Switch checked={theme === "dark"} onCheckedChange={toggle} /></div></TabsContent></Tabs></>; }