import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { useNavigate } from "react-router-dom";
import type { ColumnDef } from "@tanstack/react-table";
import { Eye, Search, ShieldAlert, UserRoundCheck } from "lucide-react";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { DataTable } from "@/components/shared/DataTable";
import { PageHeader } from "@/components/shared/PageHeader";
import { StatusBadge } from "@/components/shared/StatusBadge";
import { api } from "@/lib/api/client";
import type { AppUser } from "@/types/mokamba";

export default function UsersPage() {
  const { data = [] } = useQuery({ queryKey: ["users"], queryFn: api.users }); const [search, setSearch] = useState(""); const [status, setStatus] = useState("todos"); const [account, setAccount] = useState("todas"); const navigate = useNavigate();
  const filtered = useMemo(() => data.filter((user) => `${user.name} ${user.phone} ${user.kamba}`.toLowerCase().includes(search.toLowerCase()) && (status === "todos" || user.status === status) && (account === "todas" || user.account === account)), [data, search, status, account]);
  const columns: ColumnDef<AppUser>[] = [{ accessorKey: "name", header: "Utilizador", cell: ({ row }) => <div className="flex items-center gap-3"><Avatar><AvatarFallback className="bg-primary-soft font-bold text-primary">{row.original.initials}</AvatarFallback></Avatar><div><p className="font-bold">{row.original.name}</p><p className="text-xs text-muted-foreground">{row.original.phone}</p></div></div> }, { accessorKey: "kamba", header: "Número Kamba", cell: ({ row }) => <span className="font-mono text-sm">{row.original.kamba}</span> }, { accessorKey: "account", header: "Conta", cell: ({ row }) => <span className={row.original.account === "Real" ? "text-primary" : "text-secondary"}>{row.original.account}</span> }, { accessorKey: "status", header: "Estado", cell: ({ row }) => <StatusBadge status={row.original.status} /> }, { accessorKey: "province", header: "Província" }, { accessorKey: "lastSeen", header: "Última actividade" }, { id: "actions", header: "", enableSorting: false, cell: ({ row }) => <Button variant="ghost" size="icon" onClick={() => navigate(`/utilizadores/${row.original.id}`)} aria-label={`Ver ${row.original.name}`}><Eye /></Button> }];
  return <><PageHeader title="Utilizadores" description="Pesquise, filtre e acompanhe todas as contas Real e Número Kamba." actions={<Button><UserRoundCheck /> Acção em massa</Button>} /><section className="surface p-4 sm:p-5"><div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-[1fr_190px_190px]"><div className="relative"><Search className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Nome, telefone ou Número Kamba" className="h-11 rounded-full bg-element pl-11" /></div><Select value={status} onValueChange={setStatus}><SelectTrigger className="h-11 rounded-full"><SelectValue placeholder="Estado" /></SelectTrigger><SelectContent><SelectItem value="todos">Todos os estados</SelectItem><SelectItem value="activa">Activa</SelectItem><SelectItem value="suspensa">Suspensa</SelectItem><SelectItem value="banida">Banida</SelectItem><SelectItem value="pendente">Pendente</SelectItem></SelectContent></Select><Select value={account} onValueChange={setAccount}><SelectTrigger className="h-11 rounded-full"><SelectValue placeholder="Conta" /></SelectTrigger><SelectContent><SelectItem value="todas">Todas as contas</SelectItem><SelectItem value="Real">Real</SelectItem><SelectItem value="Número Kamba">Número Kamba</SelectItem></SelectContent></Select></div>{filtered.length ? <DataTable data={filtered} columns={columns} selectable mobileCard={(user) => <div className="flex items-center gap-3"><Avatar><AvatarFallback className="bg-primary-soft text-primary">{user.initials}</AvatarFallback></Avatar><div className="min-w-0 flex-1"><p className="font-bold">{user.name}</p><p className="text-xs text-muted-foreground">{user.phone} · {user.kamba}</p><div className="mt-2"><StatusBadge status={user.status} /></div></div><Button variant="ghost" size="icon" onClick={() => navigate(`/utilizadores/${user.id}`)}><Eye /></Button></div>} /> : <div className="py-16 text-center"><ShieldAlert className="mx-auto h-10 w-10 text-muted-foreground" /><p className="mt-4 font-bold">Nenhum utilizador encontrado</p><p className="text-sm text-muted-foreground">Altere os filtros para ver outros resultados.</p></div>}</section></>;
}