import { useQuery } from "@tanstack/react-query";
import { Ban, Eye, Search, UsersRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ConfirmAction } from "@/components/shared/ConfirmAction";
import { PageHeader } from "@/components/shared/PageHeader";
import { StatusBadge } from "@/components/shared/StatusBadge";
import { api } from "@/lib/api/client";

export default function GroupsPage() { const { data = [] } = useQuery({ queryKey: ["groups"], queryFn: api.groups }); return <><PageHeader title="Grupos" description="Acompanhe comunidades, membros e sinais de risco na plataforma." /><section className="surface p-5"><div className="relative mb-5 max-w-lg"><Search className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input className="h-11 rounded-full bg-element pl-11" placeholder="Pesquisar grupos ou proprietários" /></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data.map((group) => <article key={group.id} className="rounded-[1.5rem] border p-5 transition hover:-translate-y-0.5 hover:shadow-soft"><div className="flex items-start justify-between"><span className="icon-bubble"><UsersRound /></span><StatusBadge status={group.status} /></div><h2 className="mt-5 font-extrabold">{group.name}</h2><p className="mt-1 text-xs text-muted-foreground">{group.id} · criado por {group.owner}</p><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-element p-3"><p className="font-extrabold">{group.members.toLocaleString("pt-PT")}</p><p className="text-xs text-muted-foreground">Membros</p></div><div className="rounded-2xl bg-element p-3"><p className="font-extrabold">{group.reports}</p><p className="text-xs text-muted-foreground">Denúncias</p></div></div><div className="mt-5 flex gap-2"><Button variant="outline" className="flex-1"><Eye /> Ver detalhes</Button><ConfirmAction title="Encerrar grupo?" description="Todos os membros perderão acesso ao grupo." action="Encerrar grupo"><Button variant="destructive" size="icon" aria-label="Encerrar grupo"><Ban /></Button></ConfirmAction></div></article>)}</div></section></>; }