import { useState } from "react";
import { BadgeCheck, Eye, EyeOff, FileText, KeyRound, MapPin, Pencil, Save, ShieldCheck, UserRound } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { FileUpload } from "@/portal/components/FileUpload";
import { EstadoBadge } from "@/portal/components/Badges";
import { documentosProdutor, produtor } from "@/inca-portal/data";
import { LocationMap } from "@/inca-portal/components/LocationMap";

export default function ProfilePage() {
  const [editing, setEditing] = useState(false);
  const [show, setShow] = useState(false);
  const [form, setForm] = useState({ telefone: produtor.profile.phone, email: "joaquim.bengui@produtor.ao", comuna: produtor.profile.location.commune ?? "Gabela" });
  return <div className="space-y-6"><div><h1 className="font-display text-lg font-bold">O Meu Cadastro</h1><p className="mt-1 text-sm text-muted-foreground">Dados pessoais, agrícolas, documentos e segurança da sua conta.</p></div>
    <Card className="overflow-hidden"><div className="gradient-primary px-6 py-6 text-primary-foreground"><div className="flex flex-wrap items-center gap-4"><Avatar className="h-16 w-16 border-2 border-primary-foreground/20"><AvatarFallback className="bg-primary-foreground/15 text-primary-foreground">JB</AvatarFallback></Avatar><div><h2 className="text-xl font-semibold">{produtor.profile.fullName}</h2><p className="text-sm text-primary-foreground/75">{produtor.registryCode} · Produtor de café</p></div><span className="ml-auto flex items-center gap-2 rounded-md bg-primary-foreground/15 px-3 py-1.5 text-xs font-semibold"><BadgeCheck className="h-4 w-4" />Cadastro activo</span></div></div><CardContent className="p-6"><div className="mb-4 flex justify-between"><h3 className="font-semibold">Dados do produtor</h3><Button size="sm" variant={editing ? "default" : "outline"} onClick={() => { if (editing) toast.success("Dados actualizados (demonstração)."); setEditing(!editing); }}>{editing ? <><Save className="mr-2 h-4 w-4" />Guardar</> : <><Pencil className="mr-2 h-4 w-4" />Actualizar dados</>}</Button></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{[
      [UserRound, "Nome completo", produtor.profile.fullName], [FileText, "Identificação", `${produtor.profile.identification.type} · ${produtor.profile.identification.number}`], [ShieldCheck, "Registo INCA", produtor.registryCode], [MapPin, "Localização", `${produtor.profile.location.municipality}, ${produtor.profile.location.province}`],
    ].map(([Icon, label, value]) => { const Comp = Icon as typeof UserRound; return <div key={String(label)} className="rounded-lg border p-3"><Comp className="mb-2 h-4 w-4 text-primary" /><p className="text-[11px] font-semibold uppercase text-muted-foreground">{String(label)}</p><p className="mt-1 text-sm font-medium">{String(value)}</p></div>; })}{["telefone", "email", "comuna"].map((field) => <div key={field} className="space-y-2"><Label htmlFor={field}>{field === "telefone" ? "Telefone" : field === "email" ? "Correio electrónico" : "Comuna"}</Label><Input id={field} disabled={!editing} value={form[field as keyof typeof form]} onChange={(event) => setForm({ ...form, [field]: event.target.value })} /></div>)}</div></CardContent></Card>
    <LocationMap location={produtor.profile.location} title="Localização do produtor" description="Localização registada no cadastro do produtor de café." markerLabel={produtor.profile.fullName} />
    <Card><CardHeader><CardTitle className="text-base">Dados agrícolas</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Tempo de produção", produtor.coffeeProductionTime], ["Importância da actividade", produtor.coffeeActivityRank], ["Área de café", `${produtor.plantations[0].coffeeArea} ha`], ["Densidade", `${produtor.plantations[0].density} plantas/ha`]].map(([label, value]) => <div key={label} className="rounded-lg bg-muted/45 p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-semibold">{value}</p></div>)}</CardContent></Card>
    <Card><CardHeader><CardTitle className="text-base">Documentos do cadastro</CardTitle><p className="text-sm text-muted-foreground">Submeta um novo ficheiro apenas quando o INCA solicitar uma actualização.</p></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b bg-muted/50 text-left"><th className="p-3">Documento</th><th className="p-3">Referência</th><th className="p-3">Estado</th><th className="p-3">Actualização</th></tr></thead><tbody>{documentosProdutor.map((item) => <tr key={item.id} className="border-b"><td className="p-3 font-medium">{item.nome}</td><td className="p-3 text-muted-foreground">{item.referencia}</td><td className="p-3"><EstadoBadge estado={item.estado} /></td><td className="min-w-60 p-3">{item.estado === "Actualização solicitada" ? <FileUpload label="Novo ficheiro" /> : <span className="text-xs text-muted-foreground">Sem acção necessária</span>}</td></tr>)}</tbody></table></div></CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><KeyRound className="h-4 w-4 text-primary" />Palavra-passe</CardTitle></CardHeader><CardContent><div className="grid gap-4 md:grid-cols-3">{["Actual", "Nova", "Confirmar nova"].map((label) => <div className="space-y-2" key={label}><Label>{label}</Label><Input type={show ? "text" : "password"} /></div>)}</div><div className="mt-4 flex gap-2"><Button onClick={() => toast.success("Palavra-passe actualizada (demonstração).")}>Actualizar palavra-passe</Button><Button variant="outline" onClick={() => setShow(!show)}>{show ? <EyeOff className="mr-2 h-4 w-4" /> : <Eye className="mr-2 h-4 w-4" />}{show ? "Ocultar" : "Mostrar"}</Button></div></CardContent></Card>
  </div>;
}