import { useState } from "react";
import { CalendarDays,CheckCircle2,Clock,Plus,TriangleAlert } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Tabs,TabsContent,TabsList,TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { KpiCard,PageTitle,SolutionChip } from "../components/Common";
import { useBrain } from "../store/BrainStore";
export function FollowUpsPage(){const b=useBrain(),[finish,setFinish]=useState<string|null>(null),[result,setResult]=useState("");const groups={Hoje:b.followUps.filter(f=>f.status==="Pendente").slice(0,6),Atrasados:b.followUps.filter(f=>f.status==="Atrasado"),Próximos:b.followUps.filter(f=>f.status==="Pendente").slice(6),Concluídos:b.followUps.filter(f=>f.status==="Concluído")};return <><PageTitle title="Follow-ups" subtitle="Mantenha cada oportunidade em movimento." actions={<Button><Plus/> Registar follow-up</Button>}/><div className="mb-6 grid gap-4 sm:grid-cols-3"><KpiCard label="Hoje" value={6} icon={Clock} change="Prioridade"/><KpiCard label="Atrasados" value={groups.Atrasados.length} icon={TriangleAlert} change="Requer atenção" tone="critical"/><KpiCard label="Próximos 7 dias" value={10} icon={CalendarDays}/></div><Tabs defaultValue="Hoje"><TabsList>{Object.keys(groups).map(g=><TabsTrigger key={g} value={g}>{g}</TabsTrigger>)}</TabsList>{Object.entries(groups).map(([name,items])=><TabsContent value={name} key={name} className="surface overflow-hidden"><div className="divide-y">{items.map(f=>{const l=b.leads.find(x=>x.id===f.leadId),c=b.contacts.find(x=>x.id===l?.contactId);return <div key={f.id} className="grid gap-3 p-4 md:grid-cols-[1fr_1fr_.7fr_.9fr_auto] md:items-center"><span><strong className="block text-sm">{c?.fullName}</strong><small className="text-muted-foreground">{c?.company}</small></span>{l&&<SolutionChip value={l.mainSolution}/>}<span className="text-xs text-muted-foreground">{new Date(f.dueDate).toLocaleDateString("pt-PT",{day:"2-digit",month:"short",year:"numeric"})}</span><span className="text-sm">{f.action}</span>{f.status!=="Concluído"?<Button size="sm" variant="outline" onClick={()=>setFinish(f.id)}><CheckCircle2/> Concluir</Button>:<span className="text-xs text-success">Concluído</span>}</div>})}</div></TabsContent>)}</Tabs><Dialog open={!!finish} onOpenChange={()=>setFinish(null)}><DialogContent><DialogHeader><DialogTitle>Concluir follow-up</DialogTitle><DialogDescription>Registe o resultado para adicionar à linha de actividade do lead.</DialogDescription></DialogHeader><Label>Resultado</Label><Textarea value={result} onChange={e=>setResult(e.target.value)} placeholder="Ex.: Apresentação enviada e demonstração confirmada."/><Button onClick={()=>{if(finish&&result){b.completeFollowUp(finish,result).then(()=>{setFinish(null);setResult("");toast.success("Follow-up concluído")}).catch(err=>toast.error(err instanceof Error?err.message:"Erro ao concluir follow-up"))}}}>Guardar resultado</Button></DialogContent></Dialog></>}
export function MeetingsPage(){const b=useBrain(),[view,setView]=useState("lista");const sorted=[...b.meetings].sort((a,z)=>a.start.localeCompare(z.start));return <><PageTitle title="Reuniões" subtitle="Agenda comercial do Angola Hub Summit 2026." actions={<Button><Plus/> Nova reunião</Button>}/><Tabs value={view} onValueChange={setView}><TabsList><TabsTrigger value="mes">Mês</TabsTrigger><TabsTrigger value="semana">Semana</TabsTrigger><TabsTrigger value="lista">Lista</TabsTrigger></TabsList><TabsContent value="lista" className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{sorted.map(m=>{const l=b.leads.find(x=>x.id===m.leadId),c=b.contacts.find(x=>x.id===l?.contactId);return <article key={m.id} className="surface border-l-[3px] border-l-primary p-5"><div className="flex justify-between"><span className="rounded-full bg-accent px-2 py-1 text-xs font-medium text-accent-foreground">{m.type}</span><span className="text-xs tabular-nums text-muted-foreground">{new Date(m.start).toLocaleTimeString("pt-PT",{hour:"2-digit",minute:"2-digit"})}</span></div><h2 className="mt-4 font-semibold">{c?.fullName}</h2><p className="text-sm text-muted-foreground">{c?.company} · {l?.mainSolution}</p><p className="mt-4 text-xs text-muted-foreground">{new Date(m.start).toLocaleDateString("pt-PT",{weekday:"long",day:"2-digit",month:"long"})} · {m.location}</p></article>})}</TabsContent><TabsContent value="mes"><CalendarGrid/></TabsContent><TabsContent value="semana"><CalendarGrid week/></TabsContent></Tabs></>}
function CalendarGrid({week=false}:{week?:boolean}){const days=week?7:35;return <div className="mt-5 grid grid-cols-7 overflow-hidden rounded-lg border bg-card">{["Seg","Ter","Qua","Qui","Sex","Sáb","Dom"].map(d=><div key={d} className="bg-muted p-3 text-center text-xs font-medium uppercase text-muted-foreground">{d}</div>)}{Array.from({length:days},(_,i)=><button key={i} className="min-h-24 border-r border-t p-2 text-left text-xs hover:bg-muted"><span className="tabular-nums text-muted-foreground">{i+1}</span>{i===3&&<span className="mt-2 block rounded bg-primary p-1 text-primary-foreground">10:00 Demo RIVO</span>}{i===5&&<span className="mt-2 block rounded bg-secondary p-1 text-secondary-foreground">14:00 Reunião</span>}</button>)}</div>}
