import { useState } from "react";
import { CheckCircle2,Eye,EyeOff,LockKeyhole,Mail,User } from "lucide-react";
import { Navigate,useNavigate } from "react-router-dom";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { BrainBrand } from "../components/Brand";
import { useBrain } from "../store/BrainStore";
type Mode="login"|"register";
export default function LoginPage(){const b=useBrain(),nav=useNavigate(),[visible,setVisible]=useState(false),[mode,setMode]=useState<Mode>("login"),[busy,setBusy]=useState(false),[sent,setSent]=useState(false);
 const [login,setLogin]=useState({email:"",password:""});
 const [form,setForm]=useState({name:"",email:"",role:"",password:"",confirm:""});
 if(b.authenticated)return <Navigate to="/" replace/>;
 const submitLogin=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{await b.login(login.email,login.password);nav("/")}catch(err){toast.error(err instanceof Error?err.message:"Não foi possível entrar")}finally{setBusy(false)}};
 const submitRegister=async(e:React.FormEvent)=>{e.preventDefault();if(form.password.length<6){toast.error("A palavra-passe deve ter pelo menos 6 caracteres");return}if(form.password!==form.confirm){toast.error("As palavras-passe não coincidem");return}setBusy(true);try{await b.register({name:form.name,email:form.email,role:form.role,password:form.password});setSent(true)}catch(err){toast.error(err instanceof Error?err.message:"Não foi possível registar a conta")}finally{setBusy(false)}};
 return <div className="grid min-h-screen lg:grid-cols-2"><section className="login-pattern relative hidden flex-col justify-between bg-sidebar p-12 text-sidebar-accent-foreground lg:flex"><BrainBrand/><div className="max-w-lg"><span className="mb-6 block h-[3px] w-16 bg-sidebar-primary"/><p className="text-sm font-medium uppercase text-sidebar-foreground/50">Eventos MwangoBrain 2026</p><h1 className="mt-4 text-5xl font-semibold leading-tight">Transforme contactos em oportunidades.</h1><p className="mt-5 text-xl text-sidebar-foreground">Let's Brain together.</p></div><p className="text-xs text-sidebar-foreground/40">Mwango Brain · Creative & Technology Agency</p></section><section className="flex items-center justify-center bg-card p-6"><div className="w-full max-w-sm"><div className="mb-10 lg:hidden"><BrainBrand/></div>
 {mode==="register"&&sent?<div className="text-center"><span className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-success-soft text-success"><CheckCircle2 className="h-7 w-7"/></span><h2 className="mt-5 text-2xl font-semibold">Pedido enviado</h2><p className="mt-2 text-sm text-muted-foreground">A sua conta foi registada e aguarda aprovação de um administrador. Assim que for aprovada já pode entrar.</p><Button className="mt-6 w-full" variant="outline" onClick={()=>{setMode("login");setSent(false)}}>Voltar ao login</Button></div>
 :mode==="login"?<form onSubmit={submitLogin}><p className="text-sm font-medium text-primary">PORTAL INTERNO</p><h2 className="mt-3 text-3xl font-semibold">Bem-vindo de volta</h2><p className="mt-2 text-sm text-muted-foreground">Entre para acompanhar a participação no Summit.</p><div className="mt-8 space-y-5"><div className="space-y-2"><Label>E-mail</Label><div className="relative"><Mail className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input className="pl-10" type="email" value={login.email} onChange={e=>setLogin({...login,email:e.target.value})} required/></div></div><div className="space-y-2"><Label>Palavra-passe</Label><div className="relative"><LockKeyhole className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input className="px-10" type={visible?"text":"password"} value={login.password} onChange={e=>setLogin({...login,password:e.target.value})} required/><Button type="button" variant="ghost" size="icon" className="absolute right-0 top-0" onClick={()=>setVisible(v=>!v)} aria-label="Mostrar palavra-passe">{visible?<EyeOff/>:<Eye/>}</Button></div></div><Button className="h-11 w-full" type="submit" disabled={busy}>{busy?"A entrar…":"Entrar"}</Button><Button variant="link" className="w-full" type="button" onClick={()=>setMode("register")}>Ainda não tem conta? Registar</Button></div></form>
 :<form onSubmit={submitRegister}><p className="text-sm font-medium text-primary">PORTAL INTERNO</p><h2 className="mt-3 text-3xl font-semibold">Registar conta</h2><p className="mt-2 text-sm text-muted-foreground">O seu pedido fica pendente até ser aprovado por um administrador.</p><div className="mt-8 space-y-5"><div className="space-y-2"><Label>Nome completo</Label><div className="relative"><User className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input className="pl-10" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></div></div><div className="space-y-2"><Label>E-mail</Label><div className="relative"><Mail className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input className="pl-10" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/></div></div><div className="space-y-2"><Label>Função</Label><Input placeholder="Ex.: Comercial" value={form.role} onChange={e=>setForm({...form,role:e.target.value})} required/></div><div className="space-y-2"><Label>Palavra-passe</Label><Input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required/></div><div className="space-y-2"><Label>Confirmar palavra-passe</Label><Input type="password" value={form.confirm} onChange={e=>setForm({...form,confirm:e.target.value})} required/></div><Button className="h-11 w-full" type="submit" disabled={busy}>{busy?"A enviar…":"Pedir registo"}</Button><Button variant="link" className="w-full" type="button" onClick={()=>setMode("login")}>Já tem conta? Entrar</Button></div></form>}
 </div></section></div>}
