import { createRoot } from "react-dom/client";
import { BrowserRouter } from "react-router-dom";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Toaster } from "@/components/ui/sonner";
import { BrainProvider } from "@/brain/store/BrainStore";
import App from "./App";
import "./index.css";
const root=document.getElementById("root");
if(!root)throw new Error("Elemento principal não encontrado");
createRoot(root).render(<BrowserRouter><BrainProvider><TooltipProvider><App/><Toaster position="top-center" richColors/></TooltipProvider></BrainProvider></BrowserRouter>);