import { useState } from "react";
import { Eye, FileCheck2, History, Send } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { PageHeader } from "@/components/shared/PageHeader";
import { toast } from "sonner";

const legalText = "Bem-vindo à Mô'Kamba. Estes termos regulam a utilização responsável e segura dos serviços de mensagens, chamadas e comunidades. O utilizador compromete-se a respeitar a legislação angolana e os direitos dos restantes membros.";
export default function LegalPage() { const [text, setText] = useState(legalText); return <><PageHeader title="Termos e privacidade" description="Edite, pré-visualize e publique versões com histórico completo de aceitação." actions={<Button onClick={() => toast.success("Nova versão publicada em demonstração")}><Send /> Publicar versão</Button>} /><Tabs defaultValue="editor"><TabsList className="mb-5 rounded-full bg-element p-1"><TabsTrigger value="editor" className="rounded-full">Editor</TabsTrigger><TabsTrigger value="preview" className="rounded-full"><Eye className="mr-2 h-4 w-4" />Pré-visualização</TabsTrigger><TabsTrigger value="versions" className="rounded-full"><History className="mr-2 h-4 w-4" />Versões</TabsTrigger></TabsList><TabsContent value="editor" className="surface p-6"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-extrabold">Termos de utilização</h2><p className="text-sm text-muted-foreground">Rascunho da versão 3.3</p></div><span className="rounded-full bg-warning-soft px-3 py-1 text-xs font-bold text-warning">Não publicado</span></div><Textarea value={text} onChange={(event) => setText(event.target.value)} className="min-h-[420px] rounded-3xl bg-element p-5 leading-7" /></TabsContent><TabsContent value="preview" className="surface p-8"><p className="text-xs font-bold text-primary">MÔ'KAMBA · VERSÃO 3.3</p><h2 className="mt-3 text-3xl font-extrabold">Termos de utilização</h2><p className="mt-6 max-w-3xl whitespace-pre-line leading-8 text-muted-foreground">{text}</p></TabsContent><TabsContent value="versions" className="surface overflow-hidden">{[["v3.2", "Publicada em 15 Ago 2026", "182 490 aceitações"], ["v3.1", "Publicada em 4 Mar 2026", "157 204 aceitações"], ["v3.0", "Publicada em 10 Nov 2025", "128 944 aceitações"]].map(([v,date,count]) => <div key={v} className="flex items-center gap-4 border-b p-5 last:border-0"><span className="icon-bubble"><FileCheck2 /></span><div className="flex-1"><p className="font-bold">{v}</p><p className="text-sm text-muted-foreground">{date}</p></div><span className="text-sm font-semibold">{count}</span></div>)}</TabsContent></Tabs></>; }