import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import type { ColumnDef } from "@tanstack/react-table";
import { Download, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { DataTable } from "@/components/shared/DataTable";
import { PageHeader } from "@/components/shared/PageHeader";
import { api } from "@/lib/api/client";
import type { AuditEntry } from "@/types/mokamba";

export default function AuditPage() { const { data = [] } = useQuery({ queryKey: ["audit"], queryFn: api.audit }); const [search, setSearch] = useState(""); const filtered = useMemo(() => data.filter((item) => Object.values(item).join(" ").toLowerCase().includes(search.toLowerCase())), [data, search]); const columns: ColumnDef<AuditEntry>[] = [{ accessorKey: "time", header: "Quando" }, { accessorKey: "actor", header: "Quem", cell: ({ row }) => <span className="font-bold">{row.original.actor}</span> }, { accessorKey: "action", header: "Acção" }, { accessorKey: "target", header: "Alvo", cell: ({ row }) => <span className="font-mono text-xs">{row.original.target}</span> }, { accessorKey: "reason", header: "Motivo" }, { accessorKey: "ip", header: "IP" }]; const exportCsv = () => { const content = ["Quando,Quem,Acção,Alvo,Motivo,IP", ...data.map((item) => [item.time,item.actor,item.action,item.target,item.reason,item.ip].map((value) => `"${value}"`).join(","))].join("\n"); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([content], { type: "text/csv;charset=utf-8" })); link.download = "auditoria-mokamba.csv"; link.click(); URL.revokeObjectURL(link.href); }; return <><PageHeader title="Auditoria" description="Registo imutável e só de leitura de todas as acções administrativas." actions={<Button variant="outline" onClick={exportCsv}><Download /> Exportar CSV</Button>} /><section className="surface p-5"><div className="relative mb-5 max-w-lg"><Search className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input value={search} onChange={(e) => setSearch(e.target.value)} className="h-11 rounded-full bg-element pl-11" placeholder="Pesquisar actor, acção, alvo ou IP" /></div><DataTable data={filtered} columns={columns} mobileCard={(item) => <div><p className="font-bold">{item.action}</p><p className="text-sm">{item.actor} → {item.target}</p><p className="mt-2 text-xs text-muted-foreground">{item.reason} · {item.time}</p></div>} /></section></>; }